services:
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  schools-service-migrate:
    build: .
    env_file: .env

  schools-service:
    build: .
    env_file: .env
    ports:
      - "8000:8000"

  schools-service_db:
    ports:
      - "5432:5432"
